In [1]:
import pandas as pd

In [2]:
data=pd.read_csv(r"Downloads/Sales-Export_2019-2020.csv")

In [3]:
data

,country,order_value_EUR,cost,date,category,customer_name,sales_manager,sales_rep,device_type,order_id
0,Sweden,"17,524.02",14122.61,2/12/2020,Books,Goldner-Dibbert,Maxie Marrow,Madelon Bront,Mobile,70-0511466
1,Finland,"116,563.40",92807.78,9/26/2019,Games,Hilll-Vandervort,Hube Corey,Wat Bowkley,Mobile,28-6585323
2,Portugal,"296,465.56",257480.34,7/11/2019,Clothing,Larkin-Collier,Celine Tumasian,Smitty Culverhouse,PC,58-7703341
3,Portugal,"74,532.02",59752.32,4/2/2020,Beauty,Hessel-Stiedemann,Celine Tumasian,Aurelie Wren,PC,14-6700183
4,Spain,"178,763.42",146621.76,12/22/2019,Games,Johns and Sons,Emalia Dinse,Bertha Walbrook,Tablet,15-8765160
...,...,...,...,...,...,...,...,...,...,...
995,France,"46,296.26",40319.41,5/15/2020,Games,Wisoky Inc,Othello Bowes,Amelina Piscopiello,Tablet,77-3489084
996,Belgium,"118,061.05",101131.10,7/2/2020,Appliances,Johns and Sons,Lambert Norheny,Collin Mackness,Mobile,59-2117058
997,Finland,"74,480.56",60023.88,3/6/2020,Clothing,Homenick-Marvin,Hube Corey,Wat Bowkley,PC,31-1849120
998,Spain,"87,205.01",69171.01,6/18/2020,Games,Johns and Sons,Emalia Dinse,Manuel Goudie,Tablet,45-3085595
999,Portugal,"107,716.72",86679.64,1/18/2020,Accessories,"Jacobson, Marvin and Brown",Celine Tumasian,Brynn Dempster,Mobile,61-3294149

In [4]:
data.shape

(1000, 10)

In [5]:
data.info

<bound method DataFrame.info of       country  order_value_EUR       cost         date     category  \
0      Sweden         17,524.02   14122.61   2/12/2020        Books
1     Finland        116,563.40   92807.78   9/26/2019        Games
2    Portugal        296,465.56  257480.34   7/11/2019     Clothing
3    Portugal         74,532.02   59752.32    4/2/2020       Beauty
4       Spain        178,763.42  146621.76  12/22/2019        Games
..        ...               ...        ...         ...          ...
995    France         46,296.26   40319.41   5/15/2020        Games
996   Belgium        118,061.05  101131.10    7/2/2020   Appliances
997   Finland         74,480.56   60023.88    3/6/2020     Clothing
998     Spain         87,205.01   69171.01   6/18/2020        Games
999  Portugal        107,716.72   86679.64   1/18/2020  Accessories

                  customer_name    sales_manager            sales_rep  \
0               Goldner-Dibbert     Maxie Marrow        Madelon Bront
1              Hilll-Vandervort       Hube Corey          Wat Bowkley
2                Larkin-Collier  Celine Tumasian   Smitty Culverhouse
3             Hessel-Stiedemann  Celine Tumasian         Aurelie Wren
4                Johns and Sons     Emalia Dinse      Bertha Walbrook
..                          ...              ...                  ...
995                  Wisoky Inc    Othello Bowes  Amelina Piscopiello
996              Johns and Sons  Lambert Norheny      Collin Mackness
997             Homenick-Marvin       Hube Corey          Wat Bowkley
998              Johns and Sons     Emalia Dinse        Manuel Goudie
999  Jacobson, Marvin and Brown  Celine Tumasian       Brynn Dempster

    device_type    order_id
0        Mobile  70-0511466
1        Mobile  28-6585323
2            PC  58-7703341
3            PC  14-6700183
4        Tablet  15-8765160
..          ...         ...
995      Tablet  77-3489084
996      Mobile  59-2117058
997          PC  31-1849120
998      Tablet  45-3085595
999      Mobile  61-3294149

[1000 rows x 10 columns]>

In [7]:
data.describe()

               cost
count    1000.000000
mean    94369.310990
std     51540.020934
min     12113.680000
25%     54247.957500
50%     87094.760000
75%    125570.837500
max    304701.430000

In [8]:
data.isnull().sum()

country              0
 order_value_EUR     0
 cost                0
date                 0
category             0
customer_name        0
sales_manager        0
sales_rep            0
device_type          0
order_id             0
dtype: int64